--1
-- SELECT * FROM users;
--2
-- SELECT * FROM posts
-- WHERE users_id = 100;
--3
-- SELECT *, users.first_name, users.last_name
-- FROM posts
-- INNER JOIN users ON posts.users_id =  users.id
-- WHERE posts.users_id = 200
-- AND users.id = 200;
--4
-- SELECT posts.*, users.username
-- FROM posts
-- INNER JOIN users ON posts.users_id = users.id
-- WHERE users.first_name = 'Norene'
-- AND users.last_name = 'Schmitt';
--5
-- SELECT username
-- FROM users
-- WHERE created_at < '2015-01-01';
--6
-- SELECT posts.title, posts.content, users.username
-- FROM posts
-- INNER JOIN users ON posts.users_id = users.id
-- WHERE users.created_at < '2015-01-01';
-- 7
-- SELECT comments.*, posts.title AS "Post Title"
-- FROM comments
-- INNER JOIN posts ON posts.id = comments.posts_id
--8
-- SELECT comments.*, posts.title AS "post_title", posts.url AS "post_url", comments.body AS "comment_body"
-- FROM comments
-- INNER JOIN posts ON posts.id = comments.posts_id
-- WHERE posts.created_at < '2015-01-01';
--9
-- SELECT comments.*, posts.title AS "post_title", posts.url AS "post_url", comments.body AS "comment_body"
-- FROM comments
-- INNER JOIN posts ON posts.id = comments.posts_id
-- WHERE posts.created_at > '2015-01-01';
--10
-- SELECT comments.*, posts.title AS "post_title", posts.url AS "post_url", comments.body AS "comment_body"
-- FROM comments
-- INNER JOIN posts ON posts.id = comments.posts_id
-- WHERE comments.body LIKE '%USB%';
--11
-- SELECT posts.title AS "post_title", users.first_name, users.last_name , comments.body AS "comment_body"
-- FROM users
-- INNER JOIN posts ON users.id = posts.users_id
-- INNER JOIN comments ON posts.id = comments.posts_id
-- WHERE comments.body LIKE '%matrix%';
--12
-- SELECT  users.first_name, users.last_name , comments.body AS "comment_body"
-- FROM users
-- INNER JOIN comments ON users.id = comments.users_id
-- INNER JOIN posts ON posts.id = comments.posts_id
-- WHERE comments.body LIKE '%SSL%'
-- AND posts.content LIKE '%dolorum%';
--13
-- SELECT  users.first_name AS "post_author_first_name", users.last_name AS  "post_author_last_name", posts.title AS "post_title", comments.body AS "comment_body", users.username AS "comment_author_username"
-- FROM users
-- INNER JOIN posts ON posts.users_id = users.id
-- INNER JOIN comments ON posts.id = comments.posts_id
-- WHERE (comments.body LIKE '%SSL%'AND posts.content LIKE '%nemo%')
-- OR (comments.body LIKE '%firewall%'
-- AND posts.content LIKE '%nemo%');
